# Generated by Django 3.0.7 on 2020-06-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoComida', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.BigIntegerField()),
                ('opcoes', models.CharField(max_length=150)),
                ('valorCalorico', models.BigIntegerField()),
                ('salada', models.CharField(max_length=100)),
            ],
        ),
    ]
