# Generated by Django 3.0.7 on 2020-06-23 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('dcolheita', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='comida',
            name='opcoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comida.Opcao'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='salada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comida.Salada'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='tipoComida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comida.Tipo'),
        ),
    ]
